/**
 * GitHub publishing helpers (V1: structured review comment body).
 * Kept separate from the core ReviewEngine.
 */
import type { ReviewResult, Severity } from "../review/findings.js";
import { truncateCommentBody } from "./comment-budget.js";

const SEVERITY_LABEL: Record<Severity, string> = {
  critical: "CRITICAL",
  high: "HIGH",
  medium: "MEDIUM",
  low: "LOW",
  info: "INFO",
};

const isIncompleteReview = (summary: string): boolean =>
  /without structured findings|max iterations|malformed submit_review|ended without submit_review/i.test(
    summary,
  );

const appendFooter = (lines: string[]): void => {
  lines.push("---");
  lines.push(
    "_Generated by [PushFox](https://github.com/Anoop810/PushFox) — investigate before you review._",
  );
};

const appendInvestigated = (
  lines: string[],
  investigatedFiles: string[],
): void => {
  if (investigatedFiles.length === 0) return;
  lines.push("### Investigated");
  lines.push("");
  for (const file of investigatedFiles.slice(0, 30)) {
    lines.push(`- \`${file}\``);
  }
  lines.push("");
};

export const formatReviewMarkdown = (review: ReviewResult): string => {
  const lines: string[] = [
    "## PushFox Review",
    "",
    review.summary,
    "",
    `_Confidence: ${review.confidence}_`,
    "",
  ];

  if (isIncompleteReview(review.summary)) {
    lines.push(
      "> Review finished incompletely (investigation budget or malformed final payload). Re-run or raise `review.max_iterations` if this keeps happening.",
    );
    lines.push("");
  }

  if (review.findings.length === 0) {
    lines.push("No findings above the configured severity threshold.");
    lines.push("");
    lines.push(
      "_PushFox investigates with a Static Pack + tool loop. Empty reviews are intentional when nothing meaningful is found._",
    );
    lines.push("");
    appendInvestigated(lines, review.investigatedFiles);
    appendFooter(lines);
    return lines.join("\n");
  }

  lines.push(`### Findings (${review.findings.length})`);
  lines.push("");

  for (const finding of review.findings) {
    const loc =
      finding.line !== null
        ? `${finding.file}:${finding.line}`
        : finding.file;
    lines.push(
      `#### [${SEVERITY_LABEL[finding.severity]}] ${finding.title}`,
    );
    lines.push("");
    lines.push(`- **Where:** \`${loc}\``);
    lines.push(`- **Category:** ${finding.category}`);
    lines.push(`- **Why:** ${finding.explanation}`);
    if (finding.suggestion) {
      lines.push(`- **Suggestion:** ${finding.suggestion}`);
    }
    lines.push("");
  }

  appendInvestigated(lines, review.investigatedFiles);
  appendFooter(lines);
  return lines.join("\n");
};

export type GitHubPublishOptions = {
  token: string;
  repository: string; // owner/repo
  pullNumber: number;
  body: string;
  apiBase?: string;
};

/**
 * Posts a single PR review comment (issue comment).
 * V1 does not attempt inline line comments.
 */
export const publishPullRequestComment = async (
  options: GitHubPublishOptions,
): Promise<{ id: number; url: string }> => {
  const apiBase = options.apiBase ?? "https://api.github.com";
  const [owner, repo] = options.repository.split("/");
  if (!owner || !repo) {
    throw new Error(`Invalid repository: ${options.repository}`);
  }

  const body = truncateCommentBody(options.body);

  const response = await fetch(
    `${apiBase}/repos/${owner}/${repo}/issues/${options.pullNumber}/comments`,
    {
      method: "POST",
      headers: {
        Accept: "application/vnd.github+json",
        Authorization: `Bearer ${options.token}`,
        "X-GitHub-Api-Version": "2022-11-28",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ body }),
    },
  );

  if (!response.ok) {
    const text = await response.text();
    throw new Error(
      `GitHub API comment failed (${response.status}): ${text.slice(0, 500)}`,
    );
  }

  const data = (await response.json()) as { id: number; html_url: string };
  return { id: data.id, url: data.html_url };
};
